# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c49ead6bb8740f0d6cfdb9382b990083e25b1aa963a32d6b0ad72d82cd6e0d1dfcaa02bc4b4054d17e3ca9b9884f56e9ec3fa922805fde1d247188753606e26d

test:
  secret_key_base: 6178ba03781c242f4be823ad51707f59201344d1c82fa7ce6a90fac35aff6f5049eb21a93487dd9d7c8c382d03d2ad9d9ede2f25f69f165dc0397d33bd4dcd80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
